export const API_URL = "http://localhost:9000";

export const EDIT_SESSION_SETTINGS = "EDIT_SESSION_SETTINGS";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_CREDENTIALS = "EDIT_CREDENTIALS";
export const ERR_SUBMIT = "ERR_SUBMIT";
export const ERR_CLEAR = "ERR_CLEAR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_SET_TOKEN_NO_COOKIE = "AUTH_SET_TOKEN_NO_COOKIE";
export const LOAD_TOKEN = "LOAD_TOKEN";
export const LOAD_CREDENTIALS = "LOAD_CREDENTIALS";
export const LOAD_PROFILE = "LOAD_PROFILE";
export const MODAL_OPEN_LOGIN = "MODAL_OPEN_LOGIN";
export const MODAL_CLOSE_LOGIN = "MODAL_CLOSE_LOGIN";
export const CHANGE_SECTION = "CHANGE_SECTION";
